// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: protos/terminal_dl.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Dockers_Status int32

const (
	Dockers_OK    Dockers_Status = 0
	Dockers_ERROR Dockers_Status = 1
)

// Enum value maps for Dockers_Status.
var (
	Dockers_Status_name = map[int32]string{
		0: "OK",
		1: "ERROR",
	}
	Dockers_Status_value = map[string]int32{
		"OK":    0,
		"ERROR": 1,
	}
)

func (x Dockers_Status) Enum() *Dockers_Status {
	p := new(Dockers_Status)
	*p = x
	return p
}

func (x Dockers_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Dockers_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_terminal_dl_proto_enumTypes[0].Descriptor()
}

func (Dockers_Status) Type() protoreflect.EnumType {
	return &file_protos_terminal_dl_proto_enumTypes[0]
}

func (x Dockers_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Dockers_Status.Descriptor instead.
func (Dockers_Status) EnumDescriptor() ([]byte, []int) {
	return file_protos_terminal_dl_proto_rawDescGZIP(), []int{0, 0}
}

type Action_Action_Event int32

const (
	Action_OK    Action_Action_Event = 0
	Action_ERROR Action_Action_Event = 1
)

// Enum value maps for Action_Action_Event.
var (
	Action_Action_Event_name = map[int32]string{
		0: "OK",
		1: "ERROR",
	}
	Action_Action_Event_value = map[string]int32{
		"OK":    0,
		"ERROR": 1,
	}
)

func (x Action_Action_Event) Enum() *Action_Action_Event {
	p := new(Action_Action_Event)
	*p = x
	return p
}

func (x Action_Action_Event) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action_Action_Event) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_terminal_dl_proto_enumTypes[1].Descriptor()
}

func (Action_Action_Event) Type() protoreflect.EnumType {
	return &file_protos_terminal_dl_proto_enumTypes[1]
}

func (x Action_Action_Event) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action_Action_Event.Descriptor instead.
func (Action_Action_Event) EnumDescriptor() ([]byte, []int) {
	return file_protos_terminal_dl_proto_rawDescGZIP(), []int{1, 0}
}

type Dockers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command        string         `protobuf:"bytes,1,opt,name=Command,proto3" json:"Command,omitempty"` // dockerfile compose of keys and values
	Values         string         `protobuf:"bytes,2,opt,name=Values,proto3" json:"Values,omitempty"`
	Message_Status Dockers_Status `protobuf:"varint,3,opt,name=Message_Status,json=MessageStatus,proto3,enum=protos.Dockers_Status" json:"Message_Status,omitempty"`
}

func (x *Dockers) Reset() {
	*x = Dockers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_terminal_dl_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dockers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dockers) ProtoMessage() {}

func (x *Dockers) ProtoReflect() protoreflect.Message {
	mi := &file_protos_terminal_dl_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dockers.ProtoReflect.Descriptor instead.
func (*Dockers) Descriptor() ([]byte, []int) {
	return file_protos_terminal_dl_proto_rawDescGZIP(), []int{0}
}

func (x *Dockers) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Dockers) GetValues() string {
	if x != nil {
		return x.Values
	}
	return ""
}

func (x *Dockers) GetMessage_Status() Dockers_Status {
	if x != nil {
		return x.Message_Status
	}
	return Dockers_OK
}

type Action struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event          string              `protobuf:"bytes,1,opt,name=Event,proto3" json:"Event,omitempty"` // hold file name
	Message_Action Action_Action_Event `protobuf:"varint,2,opt,name=Message_Action,json=MessageAction,proto3,enum=protos.Action_Action_Event" json:"Message_Action,omitempty"`
}

func (x *Action) Reset() {
	*x = Action{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_terminal_dl_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_protos_terminal_dl_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_protos_terminal_dl_proto_rawDescGZIP(), []int{1}
}

func (x *Action) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *Action) GetMessage_Action() Action_Action_Event {
	if x != nil {
		return x.Message_Action
	}
	return Action_OK
}

type Program_Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Events          []*Dockers `protobuf:"bytes,1,rep,name=Events,proto3" json:"Events,omitempty"`
	OperatingEvents *Action    `protobuf:"bytes,2,opt,name=OperatingEvents,proto3" json:"OperatingEvents,omitempty"`
}

func (x *Program_Event) Reset() {
	*x = Program_Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_terminal_dl_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Program_Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Program_Event) ProtoMessage() {}

func (x *Program_Event) ProtoReflect() protoreflect.Message {
	mi := &file_protos_terminal_dl_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Program_Event.ProtoReflect.Descriptor instead.
func (*Program_Event) Descriptor() ([]byte, []int) {
	return file_protos_terminal_dl_proto_rawDescGZIP(), []int{2}
}

func (x *Program_Event) GetEvents() []*Dockers {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *Program_Event) GetOperatingEvents() *Action {
	if x != nil {
		return x.OperatingEvents
	}
	return nil
}

var File_protos_terminal_dl_proto protoreflect.FileDescriptor

var file_protos_terminal_dl_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61,
	0x6c, 0x5f, 0x64, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x22, 0x97, 0x01, 0x0a, 0x07, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x12, 0x3d, 0x0a, 0x0e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x0d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x1b, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10,
	0x00, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x22, 0x85, 0x01, 0x0a,
	0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x42, 0x0a,
	0x0e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x52, 0x0d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x21, 0x0a, 0x0c, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52,
	0x4f, 0x52, 0x10, 0x01, 0x22, 0x72, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x5f,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x27, 0x0a, 0x06, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x44,
	0x6f, 0x63, 0x6b, 0x65, 0x72, 0x73, 0x52, 0x06, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x38,
	0x0a, 0x0f, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0f, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x32, 0x77, 0x0a, 0x11, 0x54, 0x65, 0x72, 0x6d,
	0x69, 0x6e, 0x61, 0x6c, 0x44, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2c, 0x0a,
	0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x0e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x0e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x34, 0x0a, 0x04, 0x43,
	0x6f, 0x70, 0x79, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x50, 0x72, 0x6f,
	0x67, 0x72, 0x61, 0x6d, 0x5f, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x5f, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x61, 0x6c, 0x69, 0x32, 0x32, 0x31, 0x30, 0x2f, 0x64, 0x69, 0x64, 0x61, 0x63, 0x74, 0x69, 0x63,
	0x2d, 0x6f, 0x63, 0x74, 0x6f, 0x2d, 0x65, 0x75, 0x72, 0x65, 0x6b, 0x61, 0x2f, 0x6c, 0x61, 0x7a,
	0x6f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_terminal_dl_proto_rawDescOnce sync.Once
	file_protos_terminal_dl_proto_rawDescData = file_protos_terminal_dl_proto_rawDesc
)

func file_protos_terminal_dl_proto_rawDescGZIP() []byte {
	file_protos_terminal_dl_proto_rawDescOnce.Do(func() {
		file_protos_terminal_dl_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_terminal_dl_proto_rawDescData)
	})
	return file_protos_terminal_dl_proto_rawDescData
}

var file_protos_terminal_dl_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protos_terminal_dl_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_terminal_dl_proto_goTypes = []interface{}{
	(Dockers_Status)(0),      // 0: protos.Dockers.Status
	(Action_Action_Event)(0), // 1: protos.Action.Action_Event
	(*Dockers)(nil),          // 2: protos.Dockers
	(*Action)(nil),           // 3: protos.Action
	(*Program_Event)(nil),    // 4: protos.Program_Event
}
var file_protos_terminal_dl_proto_depIdxs = []int32{
	0, // 0: protos.Dockers.Message_Status:type_name -> protos.Dockers.Status
	1, // 1: protos.Action.Message_Action:type_name -> protos.Action.Action_Event
	2, // 2: protos.Program_Event.Events:type_name -> protos.Dockers
	3, // 3: protos.Program_Event.OperatingEvents:type_name -> protos.Action
	3, // 4: protos.TerminalDlService.CreateFile:input_type -> protos.Action
	4, // 5: protos.TerminalDlService.Copy:input_type -> protos.Program_Event
	3, // 6: protos.TerminalDlService.CreateFile:output_type -> protos.Action
	4, // 7: protos.TerminalDlService.Copy:output_type -> protos.Program_Event
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_protos_terminal_dl_proto_init() }
func file_protos_terminal_dl_proto_init() {
	if File_protos_terminal_dl_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_terminal_dl_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dockers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_terminal_dl_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_terminal_dl_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Program_Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_terminal_dl_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_terminal_dl_proto_goTypes,
		DependencyIndexes: file_protos_terminal_dl_proto_depIdxs,
		EnumInfos:         file_protos_terminal_dl_proto_enumTypes,
		MessageInfos:      file_protos_terminal_dl_proto_msgTypes,
	}.Build()
	File_protos_terminal_dl_proto = out.File
	file_protos_terminal_dl_proto_rawDesc = nil
	file_protos_terminal_dl_proto_goTypes = nil
	file_protos_terminal_dl_proto_depIdxs = nil
}
